// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "kansou"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/config": {
            "get": {
                "description": "Returns the current scoring config (dimensions, genres, weights). Only available when --live-config is set.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.configPayload"
                        }
                    }
                }
            },
            "post": {
                "description": "Replaces the scoring config (dimensions, genres, weights) and reloads the engine atomically. Persists to the database in DB mode, or to disk otherwise. Only available when --live-config is set.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Update config",
                "parameters": [
                    {
                        "description": "New config (config_hash is ignored)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.configPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.configPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/db-info": {
            "get": {
                "description": "Reports the active database backend, or DBless live-config status. Always available.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Database info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.dbInfoResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dimensions": {
            "get": {
                "description": "Returns the ordered list of scoring dimensions defined in server config. Use the returned keys in the scores map when calling POST /score.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "score"
                ],
                "summary": "List scoring dimensions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.dimensionsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/genres": {
            "get": {
                "description": "Returns all configured genre multiplier blocks and the primary genre blend ratio.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "score"
                ],
                "summary": "List genre multipliers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.genresResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/history": {
            "get": {
                "description": "Returns the latest score for every scored entry, ordered by scored_at descending. Requires a database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "List history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server.historyListItem"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/history/{anilist_id}": {
            "get": {
                "description": "Returns all non-deleted scores for one AniList media ID, newest first, with full breakdown. Requires a database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Show history detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AniList media ID",
                        "name": "anilist_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Score"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/history/{score_id}": {
            "delete": {
                "description": "Soft-deletes a score by its row ID (not the AniList ID). Deliberate removal from active tracking — does not promote any other score to latest. Requires a database.r",
                "tags": [
                    "history"
                ],
                "summary": "Delete a history entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "scores.id primary key",
                        "name": "score_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "hard delete (permanent removal) if true, soft delete otherwise",
                        "name": "hard",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/media/search": {
            "get": {
                "description": "Search AniList for anime or manga by name. Returns up to 5 results sorted by relevance.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Search media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Media type: ANIME or MANGA",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server.mediaResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/media/{id}": {
            "get": {
                "description": "Fetch an anime or manga entry by its AniList media ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Fetch media by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AniList media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.mediaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/score": {
            "post": {
                "description": "Calculate a weighted, genre-adjusted score for a media entry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "score"
                ],
                "summary": "Calculate score",
                "parameters": [
                    {
                        "description": "Scoring input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.scoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.scoreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/score/publish": {
            "post": {
                "description": "Write a score to the user's AniList account. Requires ANILIST_TOKEN env var.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "score"
                ],
                "summary": "Publish score",
                "parameters": [
                    {
                        "description": "Publish input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.publishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.publishResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/stats": {
            "get": {
                "description": "Returns one headline metric per stats category. Requires a database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Stats summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stats.Summary"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/dimensions": {
            "get": {
                "description": "Returns variance, consistency, correlation, skip rate, and weight override frequency per dimension. Requires a database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Dimension stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.DimensionStatsResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/genres": {
            "get": {
                "description": "Returns genre breakdown, average score by genre, and genre-dimension affinity. Requires a database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Genre stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.genreStatsResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/history": {
            "get": {
                "description": "Returns most-rescored entries, outliers, and config impact. Requires a database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "History stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.historyStatsResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/weights": {
            "post": {
                "description": "Compute per-dimension final weights for a given genre/override configuration without scoring. Used for live weight preview in the web UI.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "score"
                ],
                "summary": "Preview dimension weights",
                "parameters": [
                    {
                        "description": "Weight preview input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.weightsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.weightsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns 200 OK if the server is running.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "server.breakdownRowResponse": {
            "type": "object",
            "properties": {
                "applied_multiplier": {
                    "type": "number"
                },
                "base_weight": {
                    "type": "number"
                },
                "bias_resistant": {
                    "type": "boolean"
                },
                "contribution": {
                    "type": "number"
                },
                "effective_weight": {
                    "type": "number"
                },
                "final_weight": {
                    "type": "number"
                },
                "genre_deselected": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "primary_genre": {
                    "type": "string"
                },
                "primary_genre_multiplier": {
                    "type": "number"
                },
                "score": {
                    "type": "number"
                },
                "secondary_genres_multiplier": {
                    "type": "number"
                },
                "skipped": {
                    "type": "boolean"
                },
                "weight_override": {
                    "type": "boolean"
                }
            }
        },
        "server.configDimensionEntry": {
            "type": "object",
            "properties": {
                "bias_resistant": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "server.configPayload": {
            "type": "object",
            "properties": {
                "config_hash": {
                    "type": "string"
                },
                "dimension_order": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dimensions": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/server.configDimensionEntry"
                    }
                },
                "genres": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "number",
                            "format": "float64"
                        }
                    }
                },
                "max_history": {
                    "type": "integer"
                },
                "max_multiplier": {
                    "type": "number"
                },
                "primary_genre_weight": {
                    "type": "number"
                }
            }
        },
        "server.dbInfoResponse": {
            "type": "object",
            "properties": {
                "db": {
                    "description": "DB is \"sqlite\", \"postgres\", or null in DBless mode.",
                    "type": "string"
                },
                "live_config": {
                    "description": "LiveConfig is only present in DBless mode — it is not meaningful in DB\nmode, where config is always writable via POST /config.",
                    "type": "boolean"
                }
            }
        },
        "server.dimensionItem": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description is the scoring hint shown to the user.",
                    "type": "string"
                },
                "key": {
                    "description": "Key is the internal identifier used in the scores map of POST /score.",
                    "type": "string"
                },
                "label": {
                    "description": "Label is the human-readable display name.",
                    "type": "string"
                },
                "weight": {
                    "description": "Weight is the base weight for this dimension (all weights sum to 1.0).",
                    "type": "number"
                }
            }
        },
        "server.dimensionsResponse": {
            "type": "object",
            "properties": {
                "config_hash": {
                    "description": "ConfigHash is the SHA256 digest of the current dimensions config.\nClients can use this to detect when the dimension list has changed.",
                    "type": "string"
                },
                "dimensions": {
                    "description": "Dimensions is the ordered list of scoring dimensions.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.dimensionItem"
                    }
                }
            }
        },
        "server.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a human-readable description of what went wrong.",
                    "type": "string"
                }
            }
        },
        "server.genreMultiplierItem": {
            "type": "object",
            "properties": {
                "genre": {
                    "description": "Genre is the AniList genre name (lowercased).",
                    "type": "string"
                },
                "multipliers": {
                    "description": "Multipliers maps dimension keys to their configured multiplier values.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                }
            }
        },
        "server.genreStatsResponse": {
            "type": "object",
            "properties": {
                "genre_breakdown": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.GenreStat"
                    }
                },
                "genre_dimension_affinity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.GenreDimensionAffinity"
                    }
                },
                "score_by_genre": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.GenreScore"
                    }
                }
            }
        },
        "server.genresResponse": {
            "type": "object",
            "properties": {
                "genres": {
                    "description": "Genres is the list of configured genre multiplier blocks, sorted alphabetically.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.genreMultiplierItem"
                    }
                },
                "primary_genre_weight": {
                    "description": "PrimaryGenreWeight is the configured blend ratio for primary genre support.",
                    "type": "number"
                }
            }
        },
        "server.historyListItem": {
            "type": "object",
            "properties": {
                "anilist_id": {
                    "type": "integer"
                },
                "cover_image": {
                    "type": "string"
                },
                "entry_count": {
                    "type": "integer"
                },
                "final_score": {
                    "type": "number"
                },
                "format": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "score_id": {
                    "type": "integer"
                },
                "scored_at": {
                    "type": "string"
                },
                "title_romaji": {
                    "type": "string"
                }
            }
        },
        "server.historyStatsResponse": {
            "type": "object",
            "properties": {
                "config_impact": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.ConfigImpactStat"
                    }
                },
                "most_rescored": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.RescoredStat"
                    }
                },
                "outliers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.OutlierStat"
                    }
                }
            }
        },
        "server.mediaResponse": {
            "type": "object",
            "properties": {
                "anilist_url": {
                    "type": "string"
                },
                "average_score": {
                    "type": "integer"
                },
                "banner_image": {
                    "type": "string"
                },
                "chapters": {
                    "type": "integer"
                },
                "cover_image": {
                    "type": "string"
                },
                "episodes": {
                    "type": "integer"
                },
                "format": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "mean_score": {
                    "type": "integer"
                },
                "media_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title_english": {
                    "type": "string"
                },
                "title_native": {
                    "type": "string"
                },
                "title_romaji": {
                    "type": "string"
                }
            }
        },
        "server.publishRequest": {
            "type": "object",
            "properties": {
                "media_id": {
                    "description": "MediaID is the AniList media ID to publish the score for.",
                    "type": "integer"
                },
                "notes": {
                    "description": "Notes is an optional pre-formatted scoring breakdown to append to the\nAniList list entry notes. If the entry already has notes, the new block\nis appended after a \"---\" separator so existing content is preserved.\nOmit or leave empty to skip writing notes entirely.",
                    "type": "string",
                    "example": "Frieren: Beyond Journey's End\nScore: 9.73 / 10  [kansou]"
                },
                "score": {
                    "description": "Score is the final score to publish (e.g. 8.79).",
                    "type": "number"
                }
            }
        },
        "server.publishResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message is a human-readable confirmation.",
                    "type": "string"
                },
                "score": {
                    "description": "Score is the score that was written.",
                    "type": "number"
                },
                "title": {
                    "description": "Title is the media title as confirmed by AniList.",
                    "type": "string"
                }
            }
        },
        "server.scoreRequest": {
            "type": "object",
            "properties": {
                "media_id": {
                    "description": "MediaID is the AniList media ID of the entry being scored.",
                    "type": "integer"
                },
                "primary_genre": {
                    "description": "PrimaryGenre designates one of the media's genres as constitutive for\nblended multiplier calculation. Must match one of the active genres\n(case-insensitive). Optional — omit to use contributing-only averaging with no primary.",
                    "type": "string",
                    "example": "Mystery"
                },
                "scores": {
                    "description": "Scores maps dimension keys to user scores (1.0–10.0).\nAny configured dimension absent from this map is treated as skipped (N/A).",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "selected_genres": {
                    "description": "SelectedGenres, if non-empty, restricts multiplier calculation to this\nsubset of the media's AniList genres. Genres absent from this list but\npresent in config are recorded as deselected in the breakdown. When\nomitted, all matched config genres participate (CLI-compatible behaviour).",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "weight_overrides": {
                    "description": "WeightOverrides maps dimension keys to per-session weight overrides.\nOptional — omit to use the weights defined in server config.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                }
            }
        },
        "server.scoreResponse": {
            "type": "object",
            "properties": {
                "breakdown": {
                    "description": "Breakdown is the per-dimension audit trail.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.breakdownRowResponse"
                    }
                },
                "final_score": {
                    "description": "FinalScore is the computed weighted score (rounded to 2 decimal places).",
                    "type": "number"
                },
                "meta": {
                    "description": "Meta carries session-level provenance.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/server.sessionMetaResponse"
                        }
                    ]
                }
            }
        },
        "server.sessionMetaResponse": {
            "type": "object",
            "properties": {
                "all_genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "anilist_url": {
                    "type": "string"
                },
                "config_hash": {
                    "type": "string"
                },
                "effective_weight_sum": {
                    "type": "number"
                },
                "genres_active": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "matched_genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "media_id": {
                    "type": "integer"
                },
                "media_type": {
                    "type": "string"
                },
                "primary_genre": {
                    "type": "string"
                },
                "primary_genre_weight": {
                    "type": "number"
                },
                "title_english": {
                    "type": "string"
                },
                "title_romaji": {
                    "type": "string"
                }
            }
        },
        "server.weightDimensionRow": {
            "type": "object",
            "properties": {
                "base_weight": {
                    "description": "BaseWeight is the configured weight before genre adjustment.",
                    "type": "number"
                },
                "bias_resistant": {
                    "description": "BiasResistant indicates this dimension's multiplier is always 1.0.",
                    "type": "boolean"
                },
                "effective_weight": {
                    "description": "EffectiveWeight is BaseWeight × Multiplier before renormalization.",
                    "type": "number"
                },
                "final_weight": {
                    "description": "FinalWeight is the weight after genre adjustment, renormalization, and overrides.",
                    "type": "number"
                },
                "key": {
                    "description": "Key is the dimension's config key.",
                    "type": "string"
                },
                "label": {
                    "description": "Label is the human-readable display name.",
                    "type": "string"
                },
                "multiplier": {
                    "description": "Multiplier is the blended genre multiplier applied (1.0 when bias-resistant or no genre opinion).",
                    "type": "number"
                },
                "primary_genre_multiplier": {
                    "description": "PrimaryGenreMultiplier is the raw multiplier the primary genre defines for this\ndimension. 0 when no primary genre is set or the dimension is bias-resistant.",
                    "type": "number"
                },
                "secondary_genres_multiplier": {
                    "description": "SecondaryGenresMultiplier is the contributing-only average multiplier across\nall non-primary matched genres. 0 when no primary genre is set, when there are\nno non-primary genres (ADR-025), or when the dimension is bias-resistant.",
                    "type": "number"
                },
                "skipped": {
                    "description": "Skipped indicates this dimension is excluded from the weight pool.",
                    "type": "boolean"
                },
                "weight_override": {
                    "description": "WeightOverride indicates the final weight was set by a weight override.",
                    "type": "boolean"
                }
            }
        },
        "server.weightsRequest": {
            "type": "object",
            "properties": {
                "media_id": {
                    "description": "MediaID is the AniList media ID. Used to fetch the media's genre list.",
                    "type": "integer"
                },
                "primary_genre": {
                    "description": "PrimaryGenre designates one genre as constitutive for blended multiplier\ncalculation. Must be present in SelectedGenres when that field is provided,\notherwise must be in the media's AniList genre list.",
                    "type": "string",
                    "example": "Mystery"
                },
                "selected_genres": {
                    "description": "SelectedGenres, if non-empty, restricts the active genre set for weight\ncalculation. When omitted, all matched config genres participate.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "skipped_dimensions": {
                    "description": "SkippedDimensions maps dimension keys to true to exclude them from the\nweight pool before renormalization. Optional.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "weight_overrides": {
                    "description": "WeightOverrides maps dimension keys to per-session weight overrides.\nOptional — omit to use config weights.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                }
            }
        },
        "server.weightsResponse": {
            "type": "object",
            "properties": {
                "dimensions": {
                    "description": "Dimensions is the ordered list of per-dimension weight rows.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.weightDimensionRow"
                    }
                },
                "effective_weight_sum": {
                    "description": "EffectiveWeightSum is the sum of all per-dimension effective weights before renormalization.\nDividing any dimension's effective_weight by this value reproduces its final_weight.",
                    "type": "number"
                },
                "primary_genre_weight": {
                    "description": "PrimaryGenreWeight is the blend ratio applied when a primary genre is set (0–1).\nA value of 0.6 means 60 % primary, 40 % secondary average.",
                    "type": "number"
                }
            }
        },
        "stats.Summary": {
            "type": "object",
            "properties": {
                "lastPruneAt": {
                    "description": "LastPruneAt is nil if ` + "`" + `kansou db prune` + "`" + ` has never run.",
                    "type": "string"
                },
                "leastConsistentDim": {
                    "$ref": "#/definitions/store.DimensionVarianceStat"
                },
                "mostConsistentDim": {
                    "$ref": "#/definitions/store.DimensionVarianceStat"
                },
                "mostRescored": {
                    "description": "MostRescored is nil unless some entry has been scored more than once.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/store.RescoredStat"
                        }
                    ]
                },
                "outlierCount": {
                    "type": "integer"
                },
                "overallConsistency": {
                    "$ref": "#/definitions/store.ConsistencyStat"
                },
                "topGenre": {
                    "$ref": "#/definitions/store.GenreStat"
                },
                "topScoringGenre": {
                    "$ref": "#/definitions/store.GenreScore"
                }
            }
        },
        "store.ConfigImpactStat": {
            "type": "object",
            "properties": {
                "avgScore": {
                    "type": "number",
                    "format": "float64"
                },
                "configHash": {
                    "type": "string"
                },
                "entryCount": {
                    "type": "integer"
                },
                "firstScoredAt": {
                    "type": "string"
                },
                "lastScoredAt": {
                    "type": "string"
                }
            }
        },
        "store.ConsistencyStat": {
            "type": "object",
            "properties": {
                "avgStdDev": {
                    "type": "number",
                    "format": "float64"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "store.DimensionAvg": {
            "type": "object",
            "properties": {
                "avgScore": {
                    "type": "number",
                    "format": "float64"
                },
                "dimensionKey": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "store.DimensionCorrelationStat": {
            "type": "object",
            "properties": {
                "correlation": {
                    "description": "Pearson -1.0 to 1.0",
                    "type": "number",
                    "format": "float64"
                },
                "dimensionA": {
                    "type": "string"
                },
                "dimensionB": {
                    "type": "string"
                }
            }
        },
        "store.DimensionScoreRow": {
            "type": "object",
            "properties": {
                "applied_multiplier": {
                    "type": "number"
                },
                "base_weight": {
                    "type": "number"
                },
                "bias_resistant": {
                    "type": "boolean"
                },
                "contribution": {
                    "description": "nil if skipped",
                    "type": "number"
                },
                "dimension_key": {
                    "type": "string"
                },
                "final_weight": {
                    "type": "number"
                },
                "genre_deselected": {
                    "description": "GenreDeselected is true when a deselected genre would have contributed\nto this dimension's multiplier.",
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                },
                "primary_genre_multiplier": {
                    "description": "PrimaryGenreMultiplier is the raw multiplier the primary genre defined for\nthis dimension at scoring time. 0 when no primary genre was set or the\ndimension is bias-resistant.",
                    "type": "number"
                },
                "score": {
                    "description": "nil if skipped",
                    "type": "number"
                },
                "secondary_genres_multiplier": {
                    "description": "SecondaryGenresMultiplier is the contributing-only average multiplier\nacross non-primary matched genres at scoring time. 0 when no primary genre\nwas set, there were no secondary genres, or the dimension is bias-resistant.",
                    "type": "number"
                },
                "skipped": {
                    "type": "boolean"
                },
                "weight_override": {
                    "type": "boolean"
                }
            }
        },
        "store.DimensionStatsResponse": {
            "type": "object",
            "properties": {
                "correlation_insufficient": {
                    "description": "CorrelationInsufficient is true when no pairs met the minimum threshold.",
                    "type": "boolean"
                },
                "dimensionCorrelation": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.DimensionCorrelationStat"
                    }
                },
                "dimensionVariance": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.DimensionVarianceStat"
                    }
                },
                "scoringConsistency": {
                    "$ref": "#/definitions/store.ConsistencyStat"
                },
                "skippedDimensions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.SkippedDimStat"
                    }
                },
                "weightOverrides": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.WeightOverrideStat"
                    }
                }
            }
        },
        "store.DimensionVarianceStat": {
            "type": "object",
            "properties": {
                "avgScore": {
                    "type": "number",
                    "format": "float64"
                },
                "count": {
                    "type": "integer"
                },
                "dimensionKey": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "stdDev": {
                    "type": "number",
                    "format": "float64"
                }
            }
        },
        "store.GenreDimensionAffinity": {
            "type": "object",
            "properties": {
                "dimensions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.DimensionAvg"
                    }
                },
                "genre": {
                    "type": "string"
                }
            }
        },
        "store.GenreScore": {
            "type": "object",
            "properties": {
                "avgScore": {
                    "type": "number",
                    "format": "float64"
                },
                "count": {
                    "type": "integer"
                },
                "genre": {
                    "type": "string"
                }
            }
        },
        "store.GenreStat": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "genre": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number",
                    "format": "float64"
                }
            }
        },
        "store.MatchedGenreRow": {
            "type": "object",
            "properties": {
                "genre": {
                    "type": "string"
                },
                "is_primary": {
                    "type": "boolean"
                }
            }
        },
        "store.OutlierStat": {
            "type": "object",
            "properties": {
                "anilistID": {
                    "type": "integer"
                },
                "deviation": {
                    "description": "how many std devs from personal avg",
                    "type": "number",
                    "format": "float64"
                },
                "dimensionKey": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "personalAvg": {
                    "type": "number",
                    "format": "float64"
                },
                "score": {
                    "type": "number",
                    "format": "float64"
                },
                "scoreID": {
                    "type": "integer"
                },
                "scoredAt": {
                    "type": "string"
                },
                "titleRomaji": {
                    "type": "string"
                }
            }
        },
        "store.RescoredStat": {
            "type": "object",
            "properties": {
                "anilistID": {
                    "type": "integer"
                },
                "firstScoredAt": {
                    "type": "string"
                },
                "lastScoredAt": {
                    "type": "string"
                },
                "latestScore": {
                    "description": "LatestScore is nil if every non-deleted score for this media has had\nis_latest unset (e.g. the latest score was removed via SoftDeleteScore\nwithout a replacement being scored yet). ScoreCount is still counted\nfrom non-deleted rows regardless.",
                    "type": "number",
                    "format": "float64"
                },
                "scoreCount": {
                    "type": "integer"
                },
                "titleRomaji": {
                    "type": "string"
                }
            }
        },
        "store.Score": {
            "type": "object",
            "properties": {
                "active_genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.MatchedGenreRow"
                    }
                },
                "anilist_id": {
                    "type": "integer"
                },
                "breakdown": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.DimensionScoreRow"
                    }
                },
                "config_hash": {
                    "type": "string"
                },
                "cover_image": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "entry_count": {
                    "description": "EntryCount is the number of non-deleted scores for this media entry.\nOnly populated by ListLatest; zero on rows returned by ScoreHistory or\nLatestScore, where the caller already has the full list to count.",
                    "type": "integer"
                },
                "final_score": {
                    "type": "number"
                },
                "format": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "is_latest": {
                    "type": "boolean"
                },
                "media_type": {
                    "type": "string"
                },
                "primary_genre": {
                    "type": "string"
                },
                "primary_genre_weight": {
                    "type": "number"
                },
                "scored_at": {
                    "type": "string"
                },
                "title_english": {
                    "type": "string"
                },
                "title_romaji": {
                    "type": "string"
                },
                "user_selected_genres": {
                    "description": "UserSelectedGenres is nil if the user did not explicitly select genres.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "store.SkippedDimStat": {
            "type": "object",
            "properties": {
                "dimensionKey": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "mediaType": {
                    "type": "string"
                },
                "skipCount": {
                    "type": "integer"
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "store.WeightOverrideStat": {
            "type": "object",
            "properties": {
                "dimensionKey": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "overrideCount": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "kansou API",
	Description:      "Personal anime/manga scoring tool with AniList integration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
