// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "kansou"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dimensions": {
            "get": {
                "description": "Returns the ordered list of scoring dimensions defined in server config. Use the returned keys in the scores map when calling POST /score.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "score"
                ],
                "summary": "List scoring dimensions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.dimensionsResponse"
                        }
                    }
                }
            }
        },
        "/genres": {
            "get": {
                "description": "Returns all configured genre multiplier blocks and the primary genre blend ratio.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "score"
                ],
                "summary": "List genre multipliers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.genresResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns 200 OK if the server is running.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/media/search": {
            "get": {
                "description": "Search AniList for anime or manga by name. Returns up to 5 results sorted by relevance.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Search media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Media type: ANIME or MANGA",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server.mediaResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/media/{id}": {
            "get": {
                "description": "Fetch an anime or manga entry by its AniList media ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Fetch media by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AniList media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.mediaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/score": {
            "post": {
                "description": "Calculate a weighted, genre-adjusted score for a media entry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "score"
                ],
                "summary": "Calculate score",
                "parameters": [
                    {
                        "description": "Scoring input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.scoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.scoreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/score/publish": {
            "post": {
                "description": "Write a score to the user's AniList account. Requires ANILIST_TOKEN env var.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "score"
                ],
                "summary": "Publish score",
                "parameters": [
                    {
                        "description": "Publish input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.publishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.publishResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.breakdownRowResponse": {
            "type": "object",
            "properties": {
                "applied_multiplier": {
                    "type": "number"
                },
                "base_weight": {
                    "type": "number"
                },
                "bias_resistant": {
                    "type": "boolean"
                },
                "contribution": {
                    "type": "number"
                },
                "final_weight": {
                    "type": "number"
                },
                "genre_multipliers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "primary_genre": {
                    "type": "string"
                },
                "primary_genre_multiplier": {
                    "type": "number"
                },
                "score": {
                    "type": "number"
                },
                "skipped": {
                    "type": "boolean"
                },
                "weight_override": {
                    "type": "boolean"
                }
            }
        },
        "server.dimensionItem": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description is the scoring hint shown to the user.",
                    "type": "string"
                },
                "key": {
                    "description": "Key is the internal identifier used in the scores map of POST /score.",
                    "type": "string"
                },
                "label": {
                    "description": "Label is the human-readable display name.",
                    "type": "string"
                },
                "weight": {
                    "description": "Weight is the base weight for this dimension (all weights sum to 1.0).",
                    "type": "number"
                }
            }
        },
        "server.dimensionsResponse": {
            "type": "object",
            "properties": {
                "config_hash": {
                    "description": "ConfigHash is the SHA256 digest of the current dimensions config.\nClients can use this to detect when the dimension list has changed.",
                    "type": "string"
                },
                "dimensions": {
                    "description": "Dimensions is the ordered list of scoring dimensions.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.dimensionItem"
                    }
                }
            }
        },
        "server.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a human-readable description of what went wrong.",
                    "type": "string"
                }
            }
        },
        "server.genreMultiplierItem": {
            "type": "object",
            "properties": {
                "genre": {
                    "description": "Genre is the AniList genre name (lowercased).",
                    "type": "string"
                },
                "multipliers": {
                    "description": "Multipliers maps dimension keys to their configured multiplier values.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                }
            }
        },
        "server.genresResponse": {
            "type": "object",
            "properties": {
                "genres": {
                    "description": "Genres is the list of configured genre multiplier blocks, sorted alphabetically.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.genreMultiplierItem"
                    }
                },
                "primary_genre_weight": {
                    "description": "PrimaryGenreWeight is the configured blend ratio for primary genre support.",
                    "type": "number"
                }
            }
        },
        "server.mediaResponse": {
            "type": "object",
            "properties": {
                "anilist_url": {
                    "type": "string"
                },
                "average_score": {
                    "type": "integer"
                },
                "chapters": {
                    "type": "integer"
                },
                "cover_image": {
                    "type": "string"
                },
                "episodes": {
                    "type": "integer"
                },
                "format": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "mean_score": {
                    "type": "integer"
                },
                "media_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title_english": {
                    "type": "string"
                },
                "title_native": {
                    "type": "string"
                },
                "title_romaji": {
                    "type": "string"
                }
            }
        },
        "server.publishRequest": {
            "type": "object",
            "properties": {
                "media_id": {
                    "description": "MediaID is the AniList media ID to publish the score for.",
                    "type": "integer"
                },
                "notes": {
                    "description": "Notes is an optional pre-formatted scoring breakdown to append to the\nAniList list entry notes. If the entry already has notes, the new block\nis appended after a \"---\" separator so existing content is preserved.\nOmit or leave empty to skip writing notes entirely.",
                    "type": "string",
                    "example": "Frieren: Beyond Journey's End\nScore: 9.73 / 10  [kansou]"
                },
                "score": {
                    "description": "Score is the final score to publish (e.g. 8.79).",
                    "type": "number"
                }
            }
        },
        "server.publishResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message is a human-readable confirmation.",
                    "type": "string"
                },
                "score": {
                    "description": "Score is the score that was written.",
                    "type": "number"
                },
                "title": {
                    "description": "Title is the media title as confirmed by AniList.",
                    "type": "string"
                }
            }
        },
        "server.scoreRequest": {
            "type": "object",
            "properties": {
                "media_id": {
                    "description": "MediaID is the AniList media ID of the entry being scored.",
                    "type": "integer"
                },
                "primary_genre": {
                    "description": "PrimaryGenre designates one of the media's genres as constitutive for\nblended multiplier calculation. Must match one of the media's AniList genres\n(case-insensitive). Optional — omit to use contributing-only averaging with no primary.",
                    "type": "string",
                    "example": "Mystery"
                },
                "scores": {
                    "description": "Scores maps dimension keys to user scores (1.0–10.0).\nAny configured dimension absent from this map is treated as skipped (N/A).",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "weight_overrides": {
                    "description": "WeightOverrides maps dimension keys to per-session weight overrides.\nOptional — omit to use the weights defined in server config.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                }
            }
        },
        "server.scoreResponse": {
            "type": "object",
            "properties": {
                "breakdown": {
                    "description": "Breakdown is the per-dimension audit trail.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.breakdownRowResponse"
                    }
                },
                "final_score": {
                    "description": "FinalScore is the computed weighted score (rounded to 2 decimal places).",
                    "type": "number"
                },
                "meta": {
                    "description": "Meta carries session-level provenance.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/server.sessionMetaResponse"
                        }
                    ]
                }
            }
        },
        "server.sessionMetaResponse": {
            "type": "object",
            "properties": {
                "all_genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "anilist_url": {
                    "type": "string"
                },
                "config_hash": {
                    "type": "string"
                },
                "matched_genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "media_id": {
                    "type": "integer"
                },
                "media_type": {
                    "type": "string"
                },
                "primary_genre": {
                    "type": "string"
                },
                "primary_genre_weight": {
                    "type": "number"
                },
                "title_english": {
                    "type": "string"
                },
                "title_romaji": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "kansou API",
	Description:      "Personal anime/manga scoring tool with AniList integration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
