{{- if .Values.httpRoute.enabled }}
{{- if not .Values.httpRoute.gateway.name }}{{ fail "httpRoute.gateway.name is required when httpRoute.enabled is true" }}{{- end }}
{{- if not .Values.httpRoute.gateway.namespace }}{{ fail "httpRoute.gateway.namespace is required when httpRoute.enabled is true" }}{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "kansou.fullname" . }}
  labels:
    {{- include "kansou.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace }}
      {{- if .Values.httpRoute.gateway.sectionName }}
      sectionName: {{ .Values.httpRoute.gateway.sectionName }}
      {{- end }}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httpRoute.path }}
      backendRefs:
        - name: {{ include "kansou.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
