{{- if not .Values.anilistToken }}{{ fail "anilistToken is required" }}{{- end }}
{{- if and (eq .Values.db.type "postgres") (not .Values.db.postgres.password) }}{{ fail "db.postgres.password is required when db.type is postgres" }}{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kansou.fullname" . }}
  labels:
    {{- include "kansou.labels" . | nindent 4 }}
type: Opaque
stringData:
  ANILIST_TOKEN: {{ .Values.anilistToken | quote }}
  {{- if eq .Values.db.type "postgres" }}
  POSTGRES_PASSWORD: {{ .Values.db.postgres.password | quote }}
  {{- end }}
