{{- if not .Values.anilistToken }}{{ fail "anilistToken is required" }}{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kansou.fullname" . }}
  labels:
    {{- include "kansou.labels" . | nindent 4 }}
type: Opaque
stringData:
  ANILIST_TOKEN: {{ .Values.anilistToken | quote }}
